name: laboratorio
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.2.0
  url_launcher: ^6.1.7
  intl: ^0.18.0 
  equatable: ^2.0.5
  firebase_database: ^11.1.3
  uuid: ^3.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/login_image.jpg
